# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

def testing_pods
  pod 'Quick'
  pod 'Nimble'
end

target 'AppTemplate' do
  use_frameworks!

end

target 'AppTemplateSpec' do
  use_frameworks!
  testing_pods
  
end
